rules:
- priority: 1
  destination: productpage
  route:
    backends:
    - tags:
      - version=v1
- priority: 1
  destination: details
  route:
    backends:
    - tags:
      - version=v1
- priority: 1
  destination: ratings
  route:
    backends:
    - tags:
      - version=v1
- priority: 2
  destination: reviews
  match:
    headers:
      Cookie: "^(.*?;)?(user=jason)(;.*)?$"
  route:
    backends:
    - tags:
      - version=v2
- priority: 1
  destination: reviews
  route:
    backends:
    - tags:
      - version=v1
