# Copyright 2017 IBM Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#------------------
# Gateway
#------------------
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 32000
    protocol: TCP
  selector:
    name: gateway
  type: NodePort
---

apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gateway
  template:
    metadata:
      labels:
        name: gateway
    spec:
      containers:
      - name: gateway
        image: amalgam8/a8-sidecar:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        env:
        - name: A8_PROXY
          value: "true"
        - name: A8_DISCOVERY_ADAPTER
          value: kubernetes
        - name: A8_RULES_ADAPTER
          value: kubernetes
        - name: A8_KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---

#------------------
# Hello World
#------------------
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  clusterIP: None
  ports:
  - port: 5000
    protocol: TCP
    name: http
  selector:
    name: helloworld
---

apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: helloworld-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      name: helloworld
    matchExpressions:
      - {key: version, operator: In, values: [v1]}
  template:
    metadata:
      labels:
        name: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: amalgam8/a8-examples-helloworld-v1:${A8_RELEASE}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: A8_SERVICE_VERSION
          value: version=v1
---

apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: helloworld-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      name: helloworld
    matchExpressions:
      - {key: version, operator: In, values: [v2]}
  template:
    metadata:
      labels:
        name: helloworld
        version: v2
    spec:
      containers:
      - name: helloworld
        image: amalgam8/a8-examples-helloworld-v2:${A8_RELEASE}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: A8_SERVICE_VERSION
          value: version=v2
