commands:
  - cmd: [ "/usr/bin/run_filebeat.sh" ]
    env: [ "GODEBUG=netdns=go" ]
    on_exit: ignore
  - cmd: [ "/opt/microservices/productpage", "9080", "http://localhost:6379" ]
    on_exit: terminate

tcp_proxy_configs:
  - service: tcphelloworld
    listener_port: 12345
